export function paymentPage(id:string,environment:'test'|'production') {
  if(!/^[a-f0-9-]{36}$/.test(id))throw Error('INVALID_PAYMENT_REQUEST');
  const cdn=environment==='test'?'https://bt-cdn-uat.yappycloud.com/v1/cdn/web-component-btn-yappy.js':'https://bt-cdn.yappy.cloud/v1/cdn/web-component-btn-yappy.js';
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Direcciones507 | Pago</title><style>body{font:17px system-ui;background:#f4f6f9;color:#12213a;margin:0;padding:22px}main{max-width:520px;margin:30px auto;background:white;padding:26px;border-radius:18px}input,button{font:inherit;padding:12px;border:1px solid #ccd5e2;border-radius:10px;width:100%;box-sizing:border-box;margin:10px 0}a{color:#0b57d0}.hidden{display:none}</style><script type="module" src="${cdn}"></script></head><body><main><a href="/panel">Volver a mi panel</a><h1>Pago de tu dirección</h1><p id="quote">Consultando importe…</p><div id="checkout" class="hidden"><label for="alias">Celular registrado en Yappy</label><input id="alias" inputmode="numeric" maxlength="8" autocomplete="tel-national"><btn-yappy theme="blue"></btn-yappy></div><p id="message" role="status"></p><button id="refresh" class="hidden">Consultar estado del pago</button><p>La dirección continúa con su revisión administrativa.</p></main><script>
const addressId='${id}',q=document.getElementById('quote'),m=document.getElementById('message'),checkout=document.getElementById('checkout'),refresh=document.getElementById('refresh');let orderId=new URL(location.href).searchParams.get('order'),key=crypto.randomUUID(),busy=false;
async function state(){if(!orderId)return;refresh.classList.remove('hidden');const r=await fetch('/v1/user/payments/'+orderId,{cache:'no-store',credentials:'same-origin'});const v=await r.json();if(!r.ok){m.textContent='No se pudo consultar el pago.';return}m.textContent={PENDING:'Pago pendiente de confirmación.',PAID:'Pago confirmado. Tu solicitud continúa con la revisión administrativa.',FAILED:'Pago no completado. Consulta con Direcciones507 antes de reintentarlo.',CANCELLED:'Pago cancelado.',REFUNDED:'Pago reembolsado.'}[v.payment.status]||'Consulta con Direcciones507.';checkout.classList.add('hidden');}
async function init(){try{const r=await fetch('/v1/user/requests/'+addressId+'/payment',{cache:'no-store',credentials:'same-origin'});const v=await r.json();if(!r.ok)throw Error();q.textContent='Importe: $'+(v.quote.amountCents/100).toFixed(2);if(v.quote.amountCents===0){m.textContent='Este plan no requiere pago.';return}if(!orderId&&v.quote.orderId)orderId=v.quote.orderId;if(orderId){await state();return}checkout.classList.remove('hidden');const button=document.querySelector('btn-yappy');button.addEventListener('eventClick',async()=>{if(busy)return;const alias=document.getElementById('alias').value.trim();if(!/^6[0-9]{7}$/.test(alias)){m.textContent='Introduce tu celular de ocho dígitos.';return}busy=true;try{const r=await fetch('/v1/user/requests/'+addressId+'/payment',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json','idempotency-key':key},body:JSON.stringify({alias})});const v=await r.json();if(v.orderId){orderId=v.orderId;const u=new URL(location.href);u.searchParams.set('order',orderId);history.replaceState(null,'',u);refresh.classList.remove('hidden');}if(!r.ok)throw Error();button.eventPayment(v.button);m.textContent='Confirma el pago en Yappy.';}catch{m.textContent='No se pudo iniciar o confirmar el pago. Consulta su estado antes de reintentarlo.';}finally{busy=false}});button.addEventListener('eventSuccess',()=>state());button.addEventListener('eventError',()=>state());}catch{q.textContent='El pago no está disponible. Vuelve a tu panel.';}}
refresh.onclick=()=>state().catch(()=>{m.textContent='No se pudo consultar el pago.';});init();
</script></body></html>`;
}
